### ISSUE TITLE
Make a ReadMe file for this project !

### ISSUE THREAD

**Issue by mayank0508** [mayank0508/Calc#2]

**Comment by 96RadhikaJadhav** [comment]
@mayank0508  What all information you want to be included in README?

**Comment by mayank0508** [comment]
Nothing much just make it look a bit fancy, add the screenshot of the project, tell everyone what are the language used and make it look like a Readme file

**Comment by nicomartin8542** [comment]
Hi, I would like to take care of that issue.

**Comment by mayank0508** [comment]
@nicomartin8542 go on mate, do it

**Comment by nicomartin8542** [comment]
Hi, I sent you a PR to update the README.MD.

**Comment by mayank0508** [comment]
thanks, well-done mate 🤝🏻

**Comment by nicomartin8542** [comment]
You're welcome, thanks to you for the opportunity. Greetings
